export const lightTheme = {
    palette:{
        themePrimary: '#058ef7',
        themeLighterAlt: '#00060a',
        themeLighter: '#011728',
        themeLight: '#012b4a',
        themeTertiary: '#035594',
        themeSecondary: '#047dda',
        themeDarkAlt: '#1d99f8',
        themeDark: '#40a9f9',
        themeDarker: '#71bffb',
        neutralLighterAlt: '#302f2f',
        neutralLighter: '#383737',
        neutralLight: '#464444',
        neutralQuaternaryAlt: '#4e4d4d',
        neutralQuaternary: '#555454',
        neutralTertiaryAlt: '#727070',
        neutralTertiary: '#fffefd',
        neutralSecondary: '#fffefe',
        neutralPrimaryAlt: '#fffefe',
        neutralPrimary: '#fffefc',
        neutralDark: '#fffffe',
        black: '#ffffff',
        white: '#262525',
    }
};
export const darkTheme = {palette:{
    themePrimary: '#058ef7',
    themeLighterAlt: '#00060a',
    themeLighter: '#011728',
    themeLight: '#012b4a',
    themeTertiary: '#035594',
    themeSecondary: '#047dda',
    themeDarkAlt: '#1d99f8',
    themeDark: '#40a9f9',
    themeDarker: '#71bffb',
    neutralLighterAlt: '#302f2f',
    neutralLighter: '#383737',
    neutralLight: '#464444',
    neutralQuaternaryAlt: '#4e4d4d',
    neutralQuaternary: '#555454',
    neutralTertiaryAlt: '#727070',
    neutralTertiary: '#fffefd',
    neutralSecondary: '#fffefe',
    neutralPrimaryAlt: '#fffefe',
    neutralPrimary: '#fffefc',
    neutralDark: '#fffffe',
    black: '#ffffff',
    white: '#262525',
}
};