export const GETTING_PAWS_REQUEST = 'GETTING_PAWS_REQUEST';
export const GETTING_PAWS_SUCCESS = 'GETTING_PAWS_SUCCESS';
export const GETTING_PAWS_FAILURE = 'GETTING_PAWS_FAILURE'

export const COMMISSIONING_PAWS_REQUEST = 'COMMISSIONING_PAWS_REQUEST';
export const COMMISSIONING_PAWS_SUCCESS = 'COMMISSIONING_PAWS_SUCCESS';
export const COMMISSIONING_PAWS_FAILURE = 'COMMISSIONING_PAWS_FAILURE';

export const DECOMMISSIONING_PAW_SELECTED = 'DECOMMISSIONING_PAW_SELECTED';
export const DECOMMISSIONING_PAWS_REQUEST = 'DECOMMISSIONING_PAWS_REQUEST';
export const DECOMMISSIONING_PAWS_SUCCESS = 'DECOMMISSIONING_PAWS_SUCCESS';
export const DECOMMISSIONING_PAWS_FAILURE = 'DECOMMISSIONING_PAWS_FAILURE';

export const SELECT_DEVICES_TO_COMMISSION_PAW = 'SELECTED_DEVICES_TO_COMMISSION_PAW';
export const SELECT_PAW_TYPE_TO_COMMISSION = 'SELECT_PAW_TYPE_TO_COMMISSION';
export const REMOVE_DEVICE_FROM_COMMISSION_PAW_LIST = 'REMOVE_DEVICE_FROM_COMMISSION_PAW_LIST';
