export const GETTING_PAWS_REQUEST = 'GETTING_PAWS_REQUEST';
export const GETTING_PAWS_SUCCESS = 'GETTING_PAWS_SUCCESS';
export const GETTING_PAWS_FAILURE = 'GETTING_PAWS_FAILURE'

export const COMMISSIONING_PAWS_REQUEST = 'COMMISSIONING_PAWS_REQUEST';
export const COMMISSIONING_PAWS_SUCCESS = 'COMMISSIONING_PAWS_SUCCESS';
export const COMMISSIONING_PAWS_FAILURE = 'COMMISSIONING_PAWS_FAILURE';

